"""Промпты пайплайна генерации кейса — заглушки вместо продуктовых системных инструкций."""

from services.ai_payload import MINIMAL_SYSTEM_MESSAGE

GUIDE_DOCUMENT_DEFINITION = MINIMAL_SYSTEM_MESSAGE
QUESTIONNAIRE_SYSTEM = MINIMAL_SYSTEM_MESSAGE
SYNTHESIS_SYSTEM = MINIMAL_SYSTEM_MESSAGE
PLANNER_SYSTEM = MINIMAL_SYSTEM_MESSAGE
STAGE_AGENT_SYSTEM = MINIMAL_SYSTEM_MESSAGE
MERGE_TITLES_SYSTEM = MINIMAL_SYSTEM_MESSAGE
REPAIR_SYSTEM = MINIMAL_SYSTEM_MESSAGE
